### Get all categories
GET http://localhost:3000/api/categories
Accept: application/json

### Create new category
POST http://localhost:3000/api/categories
Accept: application/json
Content-Type: application/json

{
  "name": "Huawei"
}

### Get category by Id
GET http://localhost:3000/api/categories/3
Accept: application/json

### Update category by id
PUT http://localhost:3000/api/categories/5
Accept: application/json
Content-Type: application/json

{
  "name" : ""
}

### Delete category by Id
DELETE http://localhost:3000/api/categories/900
Accept: application/json
